version: '3.1'
services:
  mongo:
    image: mongo
    container_name: "mongo1"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongoData/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
  mongo-express:
    image: mongo-express
    restart: always 
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456