FROM node:latest 
#移动当前目录下面的文件到app目录下 
ADD . /app/ 
# #进入到app目录下面，类似cd 
WORKDIR /app 
#安装依赖 
ENV TZ Asia/Shanghai
ARG registry=https://registry.npm.taobao.org
ARG disturl=https://npm.taobao.org/dist
RUN yarn config set disturl $disturl
RUN yarn config set registry $registry
RUN yarn install
# RUN yarn --frozen-lockfile --production
#对外暴露的端口 
EXPOSE 7001 
#程序启动脚本 
CMD ["npm", "run", "start"]
